development:
    adapter: postgresql
    database: robotdb
    pool: 5
    timeout: 5000
    
test: 
    adapter: postgresql
    databse: robotdb
    pool: 5
    timeout: 5000
    
production:
  adapter: postgresql
  database: <%= ENV['RDS_DB_NAME'] %>
  encoding: unicode
  host: <%= ENV['RDS_HOSTNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
