development:
    adapter: postgresql
    database: robotdb
    pool: 5
    timeout: 5000
    
test: 
    adapter: postgresql
    databse: robotdb
    pool: 5
    timeout: 5000
    
production:
    adapter: postgresql
    databse: robotdb
    pool: 5
    timeout: 5000